# Generated by Django 3.2.5 on 2021-08-03 04:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_book_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 4, 32, 17, 899342, tzinfo=utc)),
        ),
    ]
