# Generated by Django 3.2.5 on 2021-08-03 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.EmailField(default='poormima@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 6, 1, 1, 942756, tzinfo=utc)),
        ),
    ]
