# Generated by Django 3.2.5 on 2021-08-03 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210802_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 6, 20, 2, 711758, tzinfo=utc)),
        ),
    ]
