# Generated by Django 3.2.5 on 2021-08-04 04:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20210803_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 4, 56, 43, 448103, tzinfo=utc)),
        ),
    ]
