# Generated by Django 3.2.5 on 2021-08-05 06:07

import app1.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 6, 7, 3, 961368, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.EmailField(default='poormima@gmail.com', max_length=254, validators=[app1.models.validate_email]),
        ),
    ]
