# Generated by Django 3.2.5 on 2021-08-05 06:22

import app1.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.CharField(default='comment#', max_length=100, validators=[app1.models.validate_comment]),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 6, 22, 19, 587770, tzinfo=utc)),
        ),
    ]
