# Generated by Django 3.2.5 on 2021-08-05 06:27

import app1.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20210804_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 6, 27, 27, 480266, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=100, validators=[app1.models.validate_dehli, app1.models.validate_indiagate]),
        ),
    ]
