# Generated by Django 3.2.5 on 2021-08-05 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_auto_20210804_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 7, 25, 0, 759479, tzinfo=utc)),
        ),
    ]
