# Generated by Django 3.2.5 on 2021-08-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book2',
            name='profile',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='book2',
            name='resume',
            field=models.FileField(null=True, upload_to='media/userfiles/'),
        ),
    ]
