# Generated by Django 3.2.5 on 2021-08-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20210803_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book2',
            name='profile',
            field=models.ImageField(null=True, upload_to='media/images/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='book2',
            name='resume',
            field=models.FileField(null=True, upload_to='media/userfiles/%y/%m/%d/'),
        ),
    ]
