# Generated by Django 3.2.5 on 2021-08-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20210803_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('M', 'male')], max_length=100, null=True),
        ),
    ]
